### PR TITLE
Windows OS fix

### PR DESCRIPTION
**Pull request by alptugan**
- Examples were fixed for Windows OS, Visual Studio 2022, oF v0.12
- Fixed logical operators in Interpolator.h and CollectionHelper.h

### CODE REVIEW

**Comment by roymacdonald** [comment]
Hi. Many thanks. 
None of those .vs folders should be part of the commit.
Those are bulky and are generated by VS . So please remove those. 

Did you need to do anything in particular to the VS project or were you able to compile immediately after generating with Project Generator?

**Review by alptugan — COMMENTED** [review]
Hi @roymacdonald, I removed all of the .vs hidden folders.

**Comment by roymacdonald** [comment]
awesome. Thank you very much. Merging.

**Comment by roymacdonald** [comment]
@alptugan just for your info. you did not delete the .vs folder from the git history. Which made the whole repo to go from a few MB to 100+ MB. 
For future reference, when you run git rm it will not remove those files from history, meaning, if they were commited earlier.
For that you need to use something like [git-filter-repo](https://github.com/newren/git-filter-repo)
I used the following command
`git filter-repo --path example-colorSchemeAndParametersAdjustment/.vs --path example-multiWindowOneApp/.vs --path example-basic/.vs --path example-allParameterTypes/.vs --invert-paths --force`

Then I had to do a forced push to github

cheers

**Comment by alptugan** [comment]
@roymacdonald thanks for the tip! 
The Windows machine is not my personal computer, so I deleted the folders on the Github web. I pushed the repo after making the fixes and left the machine for the project I was working on. 

Anyway, I cloned the merged repo of yours and my forked version on my M2 laptop. Everything works fine on the Mac as well. (Mac OS Ventura, oF v0.12)

Best 🖖🏻

**Pull request merged**
